{
 "title": "API Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "route",
    "query": "label_values(djq_http_requests_total, route)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests In Flight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "djq_http_requests_in_flight" }
   ]
  },
  {
   "title": "Global 4xx Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(djq_http_requests_total{status=~\"4..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Global 5xx Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(djq_http_requests_total{status=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Request Rate by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(djq_http_requests_total{route=~\"$route\"}[1m])) by (route, method)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "HTTP Response Status Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(djq_http_requests_total{route=~\"$route\"}[1m])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "P95 Latency by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(djq_http_request_duration_seconds_bucket{route=~\"$route\"}[1m])) by (le, route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "P50 Latency by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(djq_http_request_duration_seconds_bucket{route=~\"$route\"}[1m])) by (le, route))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}