{
 "title": "Distributed Job Queue - Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job_id", "label": "Search by Job ID (Optional)" }
  ]
 },
 "panels": [
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"api\"} | json | line_format \"{{.message}} (Level: {{.level}})\" |~ \"(?i).*$job_id.*\""
    }
   ]
  },
  {
   "title": "Worker Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"worker\"} | json | line_format \"{{.message}} (Level: {{.level}})\" |~ \"(?i).*$job_id.*\""
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{service=\"api\"} | json | level=~\"(?i)ERROR|WARN\" |~ \"(?i).*$job_id.*\""
    }
   ]
  },
  {
   "title": "Worker Errors / Failures / DLQ",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{service=\"worker\"} | json | level=~\"(?i)ERROR|WARN\" or status=~\"(?i)failed|retrying|dlq\" |~ \"(?i).*$job_id.*\""
    }
   ]
  }
 ]
}