apiVersion: v1
kind: ConfigMap
metadata:
  name: djq-config
  namespace: distributed-job-queue
data:
  PORT: "8080"
  WORKER_COUNT: "3"
  REDIS_URL: "redis://redis:6379"
  # DATABASE_URL will be constructed from config and secret via env mapping in the deployment
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "djq_db"
  POSTGRES_USER: "djq"
