apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: distributed-job-queue

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - frontend.yaml
  - grafana.yaml
  - loki.yaml
  - alloy.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - ../grafana/dashboards/overview.json
      - ../grafana/dashboards/api.json
      - ../grafana/dashboards/jobs-workers.json
      - ../grafana/dashboards/logs.json
