apiVersion: v1
kind: Secret
metadata:
  name: djq-secret
  namespace: distributed-job-queue
type: Opaque
stringData:
  # NOTE: Do NOT commit real production passwords to git!
  # These are dummy values for local development.
  POSTGRES_PASSWORD: "djqpassword"
